name: CI

on: [push]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - uses: docker://lpenz/ghaction-cmake:latest

  test:
    name: test
    steps:
      - ls -la .
